/*
 * File: app/view/MyGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.mygridpanel',

    height: 174,
    title: 'ตารางข้อมูลสมาชิก',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'ลำดับ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'number',
                    text: 'รหัสสมาชิก'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'date',
                    text: 'ชื่อสมาชิก'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'bool',
                    text: 'เป็นสมาชิกสาขา'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'จังหวัด'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'วันจัดตั้ง'
                },
                {
                    xtype: 'actioncolumn',
                    items: [
                        {

                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});