/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    height: 111,
    layout: {
        type: 'absolute'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 40,
                    y: 40,
                    width: 180,
                    fieldLabel: 'ชื่อ',
                    labelWidth: 30,
                    name: 'name'
                },
                {
                    xtype: 'textfield',
                    x: 270,
                    y: 40,
                    width: 190,
                    fieldLabel: 'รหัส',
                    labelWidth: 30,
                    name: 'id'
                },
                {
                    xtype: 'button',
                    x: 640,
                    y: 40,
                    width: 70,
                    text: 'เพิ่ม'
                },
                {
                    xtype: 'button',
                    x: 530,
                    y: 40,
                    width: 70,
                    text: 'ค้นหา'
                }
            ]
        });

        me.callParent(arguments);
    }

});