/*
 * File: app/view/wd_add.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.wd_add', {
    extend: 'Ext.window.Window',
    alias: 'widget.wd_add',

    height: 332,
    id: 'wd_add',
    width: 643,
    title: 'เพิ่มข้อมูลสมาชิก',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 301,
                    id: 'f_addMember',
                    width: 635,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'combobox',
                            x: 290,
                            y: 40,
                            id: 'group',
                            fieldLabel: 'กลุ่ม',
                            labelWidth: 75,
                            name: 'group',
                            displayField: 'group',
                            store: 'groupStore',
                            valueField: 'group'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 40,
                            id: 'code',
                            fieldLabel: 'รหัสสมาชิก',
                            labelWidth: 75,
                            name: 'code_mem'
                        },
                        {
                            xtype: 'textfield',
                            x: 40,
                            y: 80,
                            id: 'name',
                            fieldLabel: 'ชื่อสมาชิก',
                            labelWidth: 75,
                            name: 'name'
                        },
                        {
                            xtype: 'combobox',
                            x: 40,
                            y: 120,
                            id: 'branch',
                            width: 500,
                            fieldLabel: 'สาขา:',
                            labelWidth: 75,
                            name: 'branch',
                            displayField: 'branch',
                            store: 'branchStore',
                            valueField: 'branch'
                        },
                        {
                            xtype: 'radiogroup',
                            anchor: '-200',
                            x: 40,
                            y: 160,
                            id: 'type',
                            fieldLabel: 'ประเภทสมาชิก',
                            labelWidth: 90,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    id: 'associate',
                                    labelWidth: 50,
                                    name: 'type',
                                    inputId: 'associate',
                                    boxLabel: 'สมาชิกสมทบ'
                                },
                                {
                                    xtype: 'radiofield',
                                    id: 'ordinary',
                                    labelWidth: 50,
                                    inputId: 'ordinary',
                                    boxLabel: 'สมาชิกสามัญ'
                                }
                            ]
                        },
                        {
                            xtype: 'datefield',
                            x: 40,
                            y: 200,
                            id: 'date_start',
                            fieldLabel: 'วันจัดตั้งกลุ่ม',
                            labelWidth: 75,
                            name: 'date_start'
                        },
                        {
                            xtype: 'numberfield',
                            x: 300,
                            y: 200,
                            id: 'share_first',
                            fieldLabel: 'จำนวนหุ้นถือครั้งแรก',
                            labelWidth: 110,
                            name: 'share_first'
                        },
                        {
                            xtype: 'button',
                            x: 500,
                            y: 260,
                            id: 'btn_save',
                            width: 100,
                            text: 'บันทึก'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});